### ISSUE TITLE
Index file in data

### ISSUE THREAD

**Issue by emapple** [data-dart/bookend#10]
The file https://github.com/data-dart/bookend/blob/master/data/raw/wells_indexOfTheProjectGutenbergWorksOfHGWells.txt isn't actually a text by the author, but rather a listing of the author's works. We should remove it.

**Comment by diptanil-roy** [comment]
Should I replace it with the next book on the list or just remove it for now?

**Comment by emapple** [comment]
Up to you, I'll accept either fix

**Comment by diptanil-roy** [comment]
Ok, for now, I will do this by hand. I will need to include a workaround in the code to not scrape such files. Thanks for noticing.
