### ISSUE TITLE
Erroneous '_' appearing in some words

### ISSUE THREAD

**Issue by kdettman** [data-dart/bookend#13]
Going through some of the books, I have found extra underscores pre-pended or appended to some words. For example in `austen_emma.txt` contains some words such as `_you_`. I'm not sure what to make of these. They could be markers of emphasis.
I would like to prose adding "_" to the list of garbage characters used in the cleaning step as I can't think of a case where they would be used in a legitimate word.

**Comment by emapple** [comment]
A quick look through some of the texts confirms that the underscores are probably used for emphasis. Let's add it to the list of garbage characters.

In the future, I could see scenarios where maybe use of italics or not is an indicator of authorship, but I don't trust the plain text of gutenberg to be consistent enough for us to use it as a feature.
