### ISSUE TITLE
Poe data issues

### ISSUE THREAD

**Issue by emapple** [data-dart/bookend#18]
Two of Poe's works appear to have issues:

1) https://github.com/data-dart/bookend/blob/master/data/raw/poe_theWorksOfEdgarAllanPoeTheRavenEdition.txt is an index, not a work

2) A substantial fraction of https://github.com/data-dart/bookend/blob/master/data/raw/poe_theWorksOfEdgarAllanPoevolume_1.txt is written by other authors about Poe, not by Poe

**Comment by diptanil-roy** [comment]
I addressed this in the recent commit. @emapple
