### ISSUE TITLE
snippet function

### ISSUE THREAD

**Issue by emapple** [data-dart/bookend#30]
We need more testing of the snippet function. I'm still not convinced its behavior is ideal.

For example, if I request `non_cont=True`, it should randomly choose snippets without requiring that they are contiguous. But, it doesn't seem to be fully random.

```
BookText(rawtext='This. Is. Sparta!').snippet(1, 'sent', groups=2, non_cont=True)
```
should return This. + Is., This. + Sparta!, and Is. + Sparta! with equal frequency. It never seems to return the first one.

**Comment by emapple** [comment]
Until we know for sure that `groups` > 1 will randomly sample throughout the text for snippets, I'm going to stick with repeated calls of `snippet(..., groups=1)` instead of one call with `groups` > 1

**Comment by emapple** [comment]
Also, there are extra spaces in the returned snippet. I think it's because in this line:

https://github.com/data-dart/bookend/blob/478b900182cb65d9cca2adb60aab5c44ff07aa0f/src/book.py#L283

`str.strip` is called but not actually assigned. It should be `dummy_string = dummy_string.strip()`.

Or, better, we should delete lines 279 - 283 and replace them with
```
dummy_string = ' '.join([book.text for book in return_array])
```

**Comment by diptanil-roy** [comment]
@emapple @kdettman Addressed all of this in the latest commit. Oversights. Sorry.

**Comment by kdettman** [comment]
I think this is part of a misunderstanding @diptanil-roy and I were having last night. I would also expect/want the behavior @emapple described above. I haven't looked at the new pull request yet, but I expect it would have to do with the few lines which drop tokens from the token list if they appeared in the previously generated snippet.

**Comment by diptanil-roy** [comment]
> I think this is part of a misunderstanding @diptanil-roy and I were having last night. I would also expect/want the behavior @emapple described above. I haven't looked at the new pull request yet, but I expect it would have to do with the few lines which drop tokens from the token list if they appeared in the previously generated snippet.

Yes. The fact that some snippets are more frequent than others is an artifact of getting snippets without replacement. I need the without replacement feature for my analysis. If one can add a switch for the two behaviours, that could be useful.

**Comment by emapple** [comment]
Made obsolete by #35
