### ISSUE TITLE
Indentation Error in Model.py and Issue with raw text input

### ISSUE THREAD

**Issue by diptanil-roy** [data-dart/bookend#45]
@kdettman The code has an indentation error from Line #356. 
@NikhilTilak For now, if I put a text as an input to the whole pipeline, it throws an error at your classifier. 
For example, `voter.predict("This is my test text.")`
Can you please check that?

**Comment by kdettman** [comment]
I know about the indentation error. I tried fixing it before but that was wrapped up in the whole pull debacle this morning.

**Comment by kdettman** [comment]
This will be fixed once commit `9758a0f` is merged in pull request #46

**Comment by diptanil-roy** [comment]
Will be fixed with commit from Kyle in `kd-model`.
