### ISSUE TITLE
mlxtend usage

### ISSUE THREAD

**Issue by emapple** [data-dart/bookend#54]
Right now, the [bookend analysis notebook](https://github.com/data-dart/bookend/blob/master/notebooks/bookend_analysis_notebook.ipynb) uses `mlxtend` for the ensemble voter. However, this package isn't in the environment file, so needs to be installed separately.

Either we need to add it to `environment.yml`, or remove it and use the sklearn ensemble classifier. Does the mlxtend classifier offer any advantages over sklearn? If not, I think we should revert to sklearn so we don't have to install an otherwise unnecessary package.

**Comment by diptanil-roy** [comment]
Addressed in #56.
